### PR TITLE
Bug/sppd 121/123/124/125/126/127/128/129/130

### LINKED ISSUE #121: Stat related issues
Sheriff Cartman:
PowerDamage 30 > 40

Dark Mage Craig:
PowerDuration is off, investigation needed.

All Cards with ChargedPowerRadius need x2 in that value

### LINKED ISSUE #123: Website and Bot: Radius to Diameter
Same as this bot issue but for the website: https://github.com/feinwarusoftware/awesomobot/issues/167

On the website and bot change the term Charged Power Radius to Power Range

### LINKED ISSUE #124: 'Mosquito Swarm' card should only have levels (not upgrades)
'Mosquito Swarm' (https://sppd.feinwaru.com/MosquitoSupCard) should be treated as a summon card like snake, cock, etc. Only levels 1-7 should be select-able and not the upgrades.

Currently selecting any upgrade/level causes the page to go blank with the following logs: 
image

For whoever is fixing this, first check if there's something specific that we're doing with other summons that we're not with this card cos if that's the case, this should be an easy fix.

### LINKED ISSUE #125: Captain Wendy
Her power range increases with upgrades. On site it says that base is 2 radius and in game is 4 diameter. But next upgrade is 4.1 diameter and site says 2.1 radius.

It needs to be changed into diameter on site, or the radius gains are only half of what they are now, 0.05 not 0.1.

### LINKED ISSUE #126: Deckhand Butters
Deathwish, for leader it says undefined. 
It's 10% of unit heal.
5 is rounded down.

### LINKED ISSUE #127: Medicine Woman Sharon
Charged ability, for leader it says undefined.
It's 10% of unit heal.
5 is rounded down.

### LINKED ISSUE #128: Latest PR from SPPD-113 reverted
@iTweeno you need to re-fix all the stuff that you planned on fixing with that pr. Just go through all the stuff that you were supposed to fix and see if its broken on the live site or not.

If there's anything broken, open an issue for each problem that needs fixing.

### LINKED ISSUE #129: Rounding the numbers for powers
Some numbers for powers aren't rounded as they should be.
For instance Incan Craig U40 should deal 114 to leader because it's 113.8 by calculations.
Another example is Lightning Bolt level 4, should do 57 to leader.

RedLynx rounds down numbers that end with 5 but the rest is still rounded up.
So 9.6-10.5 would all be rounded to 10 while 10.6 is rounded up to 11.

### PR DESCRIPTION
**Pull request by iTweeno**
#130 is fixed
#129 is fixed
#128 is fixed
#127 is fixed
#126 is fixed
#125 is fixed
#124 is fixed
#123 is fixed
#121 is fixed
README updated

### CODE REVIEW

File: ui/src/views/Card.jsx [hunk 1]
```diff
@@ -294,13 +294,29 @@ export default class Card extends Component {
...
+
         if (bracketless === "power_hero_damage") {
-          let powerAmount = getPowerAmount("power_hero_damage");
-          if (powerAmount == null) {
-            return getPowerAmount("power_damage") / 10;
-          }
-          else {
-            return powerAmount;
+           
+          const powerHeroDamage = getPowerAmount("power_damage");
```
Comment (Dragon1320) [inline ui/src/views/Card.jsx]: This block can be simplified significantly, try round((a - 1) / b) if you wanna round down from 5

File: .github/ISSUE_TEMPLATE/bug-report.md [hunk 2]
```diff
@@ -0,0 +1,46 @@
+---
```
Comment (Dragon1320) [inline .github/ISSUE_TEMPLATE/bug-report.md]: You're not supposed to edit this

File: .github/ISSUE_TEMPLATE/feature-request.md [hunk 3]
```diff
@@ -0,0 +1,23 @@
+---
```
Comment (Dragon1320) [inline .github/ISSUE_TEMPLATE/feature-request.md]: You're not supposed to edit this

File: .github/ISSUE_TEMPLATE/user-story.md [hunk 4]
```diff
@@ -0,0 +1,39 @@
+---
```
Comment (Dragon1320) [inline .github/ISSUE_TEMPLATE/user-story.md]: You're not supposed to edit this

File: README.md [hunk 5]
```diff
@@ -114,6 +114,10 @@ Thanks for making out day easier by taking care of the 10s of thousands of lines
 
 - [Umustalldie2](https://github.com/Umustalldie2)
 
+**Website Maintenance**
```
Comment (Dragon1320) [inline README.md]: Look at this, you're missing the sentence after the heading that's there for json editors, keep it consistent
image

File: ui/src/views/Card.jsx [hunk 6]
```diff
@@ -319,6 +335,13 @@ export default class Card extends Component {
           return getPowerAmount("power_attack_boost");
         } else if (bracketless === "power_heal") {
           return getPowerAmount("power_heal");
+        } else if (bracketless === "power_hero_heal") {
```
Comment (Dragon1320) [inline ui/src/views/Card.jsx]: Simplify the rounding, look at other similar comment

**Comment by iTweeno** [comment]
image
I didn't even touch the files inside .github

File: ui/src/translations/en-gb.js [hunk 7]
```diff
@@ -41,7 +41,7 @@ export default {
   Theme: "Theme",
   adventure: "adventure",
   fantasy: "fantasy",
-  general: "general",
+  general: "neutral",
```
Comment (MattheousDT) [inline ui/src/translations/en-gb.js]: Can this variable name be changed and the translation changed on other languages

File: ui/src/views/Card.jsx [hunk 8]
```diff
@@ -294,8 +294,17 @@ export default class Card extends Component {
           console.log ('é nulo' + alteredCard);
```
Comment (MattheousDT) [inline ui/src/views/Card.jsx]: There is a lot of code that is commented out. Could this be removed

File: ui/src/translations/en-gb.js (hunk 7 above)
Comment (iTweeno) [reply ui/src/translations/en-gb.js]: https://github.com/feinwarusoftware/sppd/issues/131
You still want me to change? Or can i just change it in the chinese ver

Comment (iTweeno) [reply ui/src/translations/en-gb.js]: Also it would require to change LOTS of stuff around the code, unless you really want the variable name to be changed, i suggest we leave it like that.

Comment (MattheousDT) [reply ui/src/translations/en-gb.js]: Just change the translation for the other versions

File: ui/src/views/Card.jsx [hunk 9]
```diff
@@ -289,13 +209,18 @@ export default class Card extends Component {
 
       if (alteredCard[bracketless] == null) {
 
+<<<<<<< HEAD
```
Comment (MattheousDT) [inline ui/src/views/Card.jsx]: Resolve this merge conflict

File: README.md [hunk 10]
```diff
@@ -114,6 +114,12 @@ Thanks for making out day easier by taking care of the 10s of thousands of lines
...
+
+Thanks for fixing the bugs that should never been there in the first time.
```
Comment (Dragon1320) [inline README.md]: grammar
